name: "Hello World"

on:

  push:
    branches: 
      - v1
      
  pull_request:
    branches: [ main ]

jobs:
  Hello-word:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v3
    - uses: ./
