name: "Hello World"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Hello-word:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: print Hello Word
      run: node index.js
